project:
    name: ecommerce_app
    version: 1.0.0
    imageFolder: poster/
    url: http://localhost:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3305/ecommerce_db
    username: user
    password: 12345
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
        id:
          new_generator_mappings: true
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    http-statuses:
      org.springframework.security.authorization.AuthorizationDeniedException: unauthorized
    codes:
      AppUserUsernameUnique: APP_USER_USERNAME_UNIQUE
springdoc:
  pathsToMatch: /api/**, /authenticate, /register

logging:
  level:
    io.bootify.ecommerce_app: DEBUG
    root: INFO
  file:
    name: logs/app-logs.log
#  pattern: %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
